from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session

from .. import models, schemas
from ..database import get_db

router = APIRouter(prefix="/aura", tags=["aura"])


@router.get("/pending", response_model=list[schemas.AuraScoreOut])
def list_pending(db: Session = Depends(get_db)):
    """Suggestions generated by the screenshot-watcher worker, awaiting admin approval."""
    return (
        db.query(models.AuraScore)
        .filter(models.AuraScore.status == models.AuraScoreStatus.suggested)
        .all()
    )


@router.post("/{aura_id}/review", response_model=schemas.AuraScoreOut)
def review_aura_score(aura_id: str, body: schemas.AuraScoreReview, admin_id: str, db: Session = Depends(get_db)):
    aura = db.query(models.AuraScore).filter(models.AuraScore.id == aura_id).first()
    if aura is None:
        raise HTTPException(status_code=404, detail="Not found")
    aura.status = body.status
    if body.points is not None:
        aura.points = body.points
    aura.entered_by = admin_id
    db.commit()
    db.refresh(aura)
    return aura
